name: Build and Deploy to Azure App Service using ACR

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env file for production
        run: |
          echo "VITE_API_BASE_URL=http://20.40.40.227:8080/" > .env
          echo "VITE_OAUTH2_REDIRECT_URL=http://app.mindxservice.ai/oauth2/redirect" >> .env
          echo "VITE_GOOGLE_AUTH_URL=http://20.40.40.227:8080/oauth2/authorize/google?redirect_uri=http://app.mindxservice.ai/oauth2/redirect" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Log in to Azure Container Registry (ACR)
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/mindx-ui:latest .

      - name: Push Docker image to ACR
        run: docker push ${{ secrets.ACR_NAME }}.azurecr.io/mindx-ui:latest

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ secrets.ACR_NAME }}.azurecr.io/mindx-ui:latest



# name: Azure Static Web Apps CI/CD

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     types: [opened, synchronize, reopened, closed]
#     branches:
#       - main

# env:
#   VITE_API_BASE_URL: https://mindx-service-api-ftbna7ambcf5g7b7.eastus-01.azurewebsites.net
#   VITE_OAUTH2_REDIRECT_URL: https://victorious-beach-0ce12d000.1.azurestaticapps.net/oauth2/redirect
#   VITE_GOOGLE_AUTH_URL: https://mindx-service-api-ftbna7ambcf5g7b7.eastus-01.azurewebsites.net/oauth2/authorize/google?redirect_uri=https://victorious-beach-0ce12d000.1.azurestaticapps.net/oauth2/redirect

# jobs:
#   build_and_deploy_job:
#     if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
#     runs-on: ubuntu-latest
#     name: Build and Deploy Job
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           submodules: true
#           lfs: false
#       - name: Build And Deploy
#         id: builddeploy
#         uses: Azure/static-web-apps-deploy@v1
#         with:
#           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_BEACH_0CE12D000 }}
#           repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
#           action: "upload"
#           ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
#           # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
#           app_location: "/" # App source code path
#           api_location: "" # Api source code path - optional
#           output_location: "dist" # Built app content directory - optional
#           ###### End of Repository/Build Configurations ######

#   close_pull_request_job:
#     if: github.event_name == 'pull_request' && github.event.action == 'closed'
#     runs-on: ubuntu-latest
#     name: Close Pull Request Job
#     steps:
#       - name: Close Pull Request
#         id: closepullrequest
#         uses: Azure/static-web-apps-deploy@v1
#         with:
#           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_BEACH_0CE12D000 }}
#           action: "close"

